apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: P1849AB3917F44AF # Matches the UID used in the dashboard JSON
