#ifndef RTOSTWIN_CONFIG_H
#define RTOSTWIN_CONFIG_H

#define RTOSTWIN_ENABLE 1
#define RTOSTWIN_ENABLE_COMPAT_API 1
#define RTOSTWIN_VERSION_STRING "test-lifecycle"
#define RTOSTWIN_TELEMETRY_TASK_NAME "RTOSTwinTest"
#define RTOSTWIN_TELEMETRY_TASK_STACK_WORDS 256
#define RTOSTWIN_TELEMETRY_TASK_PRIORITY_OFFSET 3
#define RTOSTWIN_TELEMETRY_PERIOD_MS 100
#define RTOSTWIN_PAYLOAD_BUFFER_BYTES 512
#define RTOSTWIN_FRAME_BUFFER_BYTES 540
#define RTOSTWIN_PROFILE_REPORT_INTERVAL 100
#define RTOSTWIN_ENABLE_PROFILING 0

#endif /* RTOSTWIN_CONFIG_H */
