/**
 * @file main.c
 * @brief Main entry point for the RTOSTwin Telemetry Agent.
 */

#include "FreeRTOS.h"
#include "task.h"
#include "core/snapshot.h"
#include "core/encoder.h"
#include "core/framer.h"
#include "core/transport.h"
#include "core/profiler.h"

/* 
 * Shared static buffers.
 * These are placed in the .data/.bss section to keep the 
 * telemetry task stack usage minimal.
 */
static full_snapshot_t s_current_snapshot;
static uint8_t s_payload_buffer[512];
static uint8_t s_framed_buffer[540];

/**
 * @brief Telemetry Task
 * 
 * Runs at tskIDLE_PRIORITY + 1. Captures, encodes, frames, 
 * and transmits RTOS telemetry at 10 Hz.
 */
void vTelemetryTask(void *pvParameters) {
    (void)pvParameters;

    /* Initialize all modules */
    snapshot_init();
    encoder_init();
    transport_init();
    
    profiler_stats_t snap_stats = {0};
    uint32_t loop_count = 0;

    while (1) {
        /* 1. Capture Snapshot + Profile Performance */
        uint32_t t_start = profiler_start();
        snapshot_capture(&s_current_snapshot);
        profiler_record(&snap_stats, profiler_stop(t_start));

        /* 2. Delta Encoding (Force keyframe every 50 iterations) */
        bool force_keyframe = (loop_count % 50 == 0);
        uint16_t enc_len = encoder_encode(&s_current_snapshot, 
                                          s_payload_buffer, 
                                          sizeof(s_payload_buffer), 
                                          force_keyframe);

        /* 3. Framing (Sync + Header + CRC) */
        uint16_t frame_len = frame_packet(s_payload_buffer, 
                                          enc_len, 
                                          s_framed_buffer, 
                                          sizeof(s_framed_buffer));

        /* 4. Asynchronous Transmission (DMA) */
        transport_send(s_framed_buffer, frame_len);

        /* 5. Performance Reporting (every 10 seconds at 10Hz) */
        if (++loop_count % 100 == 0) {
            profiler_report(&snap_stats, "snapshot_capture");
        }

        /* Sleep for 100ms (10 Hz rate) */
        vTaskDelay(pdMS_TO_TICKS(100));
    }
}

/**
 * @brief Main function (stub)
 * 
 * In a real STM32 project, this would be in the main.c 
 * generated by CubeMX. We show how to launch the task here.
 */
void StartTelemetryAgent(void) {
    xTaskCreate(vTelemetryTask, 
                "TelemetryTask", 
                256, 
                NULL, 
                tskIDLE_PRIORITY + 1, 
                NULL);
}
